plugins {
    id 'java-library'
    id 'eclipse'
    id 'idea'
    id 'fabric-loom' version '1.8-SNAPSHOT'
    id 'maven-publish'
}

version = mod_version
group = mod_group_id

base {
    archivesName = "${mod_name}-${mc_version}"
}

repositories {
    maven {
        name = "Jared's maven"
        url = "https://maven.blamejared.com/"
    }
    maven {
        name = "ModMaven"
        url = "https://modmaven.dev"
    }
    maven {
        url = "https://api.modrinth.com/maven"
    }
    maven {
        url = "https://maven.parchmentmc.org"
    }
    maven {
        url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven/"
    }
    maven {
        url = "https://maven.terraformersmc.com/"
    }
    flatDir {
        dirs "libs"
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.mc_version}"
    mappings loom.layered() {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-1.21:${project.parchment_version}@zip")
    }
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

    modApi "fuzs.forgeconfigapiport:forgeconfigapiport-fabric:${project.forgeconfigapiport_version}"

    modRuntimeOnly "com.terraformersmc:modmenu:${project.modmenu_version}"
}

loom {
    accessWidenerPath = file("src/main/resources/excavein.accesswidener")
}

tasks.withType(ProcessResources).configureEach {
    var replaceProperties = [
            version:            version,
            mod_id:             mod_id,
            mod_name:           mod_name,
            mod_version:        mod_version,
            mod_description:    mod_description,
            mod_authors:        mod_authors,
            mod_license:        mod_license,
            loader_version:     loader_version,
            mc_version:         mc_version
    ]
    inputs.properties replaceProperties

    filesMatching("fabric.mod.json") {
        expand replaceProperties
    }
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/repo"
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 21
    it.options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.base.archivesName.get()}"}
    }
}

java {
    withSourcesJar()
    withJavadocJar()
}